export const AGREGAR_TAREA = 'AGREGAR_TAREA'
export const AGREGAR_TAREA_EXITO = 'AGREGAR_TAREA_EXITO'
export const AGREGAR_TAREA_ERROR = 'AGREGAR_TAREA_ERROR'


export const CARGAR_TAREAS = 'CARGAR_TAREAS'
export const CARGAR_TAREAS_EXITO = 'CARGAR_TAREAS_EXITO'
export const CARGAR_TAREAS_ERROR = 'CARGAR_TAREAS_ERROR'

export const ELIMINAR_TAREA = 'ELIMINAR_TAREA'
export const ELIMINAR_TAREA_EXITO = 'ELIMINAR_TAREA_EXITO'
export const ELIMINAR_TAREA_ERROR = 'ELIMINAR_TAREA_ERROR'

