export const OBTENER_PRODUCTOS ='OBTENER_PRODUCTOS'
export const OBTENER_PRODUCTOS_EXITO ='OBTENER_PRODUCTOS_EXITO'
export const OBTENER_PRODUCTOS_ERROR ='OBTENER_PRODUCTOS_ERROR'


export const BUSCAR_PRODUCTOS ='BUSCAR_PRODUCTOS'
export const BUSCAR_PRODUCTOS_EXITO ='BUSCAR_PRODUCTOS_EXITO'
export const BUSCAR_PRODUCTOS_ERROR ='BUSCAR_PRODUCTOS_ERROR'