export const BUSCAR_CARTA = 'BUSCAR_CARTA'
export const BUSCAR_CARTA_EXITO = 'BUSCAR_CARTA_EXITO'
export const BUSCAR_CARTA_ERROR = 'BUSCAR_CARTA_ERROR'

export const GUARDAR_CARTAS = 'GUARDAR_CARTAS'
export const GUARDAR_CARTAS_EXITO = 'GUARDAR_CARTAS_EXITO'
export const GUARDAR_CARTAS_ERROR = 'GUARDAR_CARTAS_ERROR'

export const ELIMINAR_CARTA = 'ELIMINAR_CARTA'
export const ELIMINAR_CARTA_EXITO = 'ELIMINAR_CARTA_EXITO'
export const ELIMINAR_CARTA_ERROR = 'ELIMINAR_CARTA_ERROR'


export const EDITAR_CARTA = 'EDITAR_CARTA'
export const EDITAR_CARTA_EXITO = 'EDITAR_CARTA_EXITO'
export const EDITAR_CARTA_ERROR = 'EDITAR_CARTA_ERROR'


export const DESCARGAR_CARTAS = 'DESCARGAR_CARTAS'
export const DESCARGAR_CARTAS_EXITO = 'DESCARGAR_CARTAS_EXITO'
export const DESCARGAR_CARTAS_ERROR = 'DESCARGAR_CARTAS_ERROR'

export const LOGOUT = 'LOGOUT'


