export const BUSCAR_CARTA = 'BUSCAR_CARTA'
export const BUSCAR_CARTA_EXITO = 'BUSCAR_CARTA_EXITO'
export const BUSCAR_CARTA_ERROR = 'BUSCAR_CARTA_ERROR'

export const GUARDAR_CARTAS = 'GUARDAR_CARTAS'
export const GUARDAR_CARTAS_EXITO = 'GUARDAR_CARTAS_EXITO'
export const GUARDAR_CARTAS_ERROR = 'GUARDAR_CARTAS_ERROR'