export const SELECCIONAR_CONTACTO = 'SELECCIONAR_CONTACTO';

export const BUSCAR_CONEXIONES = 'BUSCAR_CONEXIONES';

export const BUSCAR_LETRA = 'BUSCAR_LETRA';

export const DESCARGAR_CONTACTOS = 'DESCARGAR_CONTACTOS';
export const DESCARGAR_CONTACTOS_EXITO = 'DESCARGAR_CONTACTOS_EXITO';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';

export const REGISTRO_ERROR = 'REGISTRO_ERROR';

export const OBTENER_USUARIO = 'OBTENER_USUARIO';

export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';

export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CERRAR_SESION = 'CERRAR_SESION';


export const BUSCAR_CONTACTO = 'BUSCAR_CONTACTO'
export const BUSCAR_CONTACTO_EXITO = 'BUSCAR_CONTACTO_EXITO'